name: localization_sheets
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: PaweĹ‚ Szot <pszot@pgs-soft.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  googleapis: any
  googleapis_auth: any
  spreadsheet_decoder: any

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

executables:
  localization_sheets: