name: localization_sheets
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Pawel‚ Szot <pszot@pgs-soft.com>
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  arb:
    git: https://github.com/szotp/dart_arb
  args: any
  collection: ^1.15.0-nullsafety.4
  googleapis: any
  googleapis_auth: any
  path: ^1.7.0
  recase: ^4.0.0-nullsafety.0
  spreadsheet_decoder: any
  yaml: any

dev_dependencies:
  crypto: ^3.0.1
  lint: ^1.1.1
  test: ^1.6.0

executables:
  ? localization_sheets
  ? arb_cleanup
